# Generated by Django 4.0 on 2022-07-24 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload2',
            name='Remark',
        ),
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('Remark', models.CharField(choices=[('P', 'P'), ('A', 'A')], default='P', max_length=1, null=True)),
                ('stud', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='System.upload2')),
            ],
        ),
    ]
