# Generated by Django 4.0 on 2022-07-25 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0002_remove_upload2_remark_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='asub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='System.faculty'),
        ),
    ]
