# Generated by Django 4.0 on 2022-07-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0003_attendance_asub'),
    ]

    operations = [
        migrations.CreateModel(
            name='HOD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('dpart', models.CharField(choices=[('Computer', 'Computer'), ('ENTC', 'ENTC'), ('INSTRU', 'INSTRU'), ('MECH', 'MECH')], max_length=20, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='faculty',
            name='div',
            field=models.CharField(choices=[('SY_A', 'SY_A'), ('SY_B', 'SY_B'), ('SY_C', 'SY_C'), ('TY_A', 'TY_A'), ('TY_B', 'TY_B'), ('TY_C', 'TY_C'), ('BTECH_A', 'BTECH_A'), ('BTECH_B', 'BTECH_B'), ('BTECH_C', 'BTECH_C')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='upload',
            name='div',
            field=models.CharField(choices=[('SY_A', 'SY_A'), ('SY_B', 'SY_B'), ('SY_C', 'SY_C'), ('TY_A', 'TY_A'), ('TY_B', 'TY_B'), ('TY_C', 'TY_C'), ('BTECH_A', 'BTECH_A'), ('BTECH_B', 'BTECH_B'), ('BTECH_C', 'BTECH_C')], default='SY_A', max_length=7, null=True),
        ),
    ]
