# Generated by Django 4.0 on 2022-08-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0004_hod_alter_faculty_div_alter_upload_div'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='dpart',
            field=models.CharField(choices=[('Computer', 'Computer'), ('ENTC', 'ENTC'), ('INSTRU', 'INSTRU'), ('MECH', 'MECH')], default='Computer', max_length=20, null=True),
        ),
    ]
