# Generated by Django 4.0 on 2022-08-01 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0005_faculty_dpart'),
    ]

    operations = [
        migrations.CreateModel(
            name='defaulter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fsub', models.CharField(choices=[('DBMS', 'DBMS'), ('CN', 'CN'), ('SDA', 'SDA'), ('DMDW', 'DMDW'), ('DSA', 'DSA')], max_length=200, null=True)),
                ('subtype', models.CharField(choices=[('theory', 'theory'), ('lab', 'lab'), ('tutorial', 'tutorial')], default='theory', max_length=20, null=True)),
                ('batch', models.CharField(max_length=200, null=True)),
                ('div', models.CharField(choices=[('SY_A', 'SY_A'), ('SY_B', 'SY_B'), ('SY_C', 'SY_C'), ('TY_A', 'TY_A'), ('TY_B', 'TY_B'), ('TY_C', 'TY_C'), ('BTECH_A', 'BTECH_A'), ('BTECH_B', 'BTECH_B'), ('BTECH_C', 'BTECH_C')], max_length=7, null=True)),
                ('dpart', models.CharField(choices=[('Computer', 'Computer'), ('ENTC', 'ENTC'), ('INSTRU', 'INSTRU'), ('MECH', 'MECH')], default='Computer', max_length=20, null=True)),
                ('fname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='System.faculty')),
            ],
        ),
    ]
