# Generated by Django 4.0 on 2022-08-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0007_rename_batch_defaulter_defaulter_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaulter',
            name='month',
            field=models.DateField(null=True),
        ),
    ]
