# Generated by Django 4.0 on 2022-08-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0008_defaulter_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defaulter',
            name='defaulter_list',
        ),
        migrations.AddField(
            model_name='defaulter',
            name='defaulter_list',
            field=models.ManyToManyField(to='System.Upload2'),
        ),
    ]
